on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Debug SSH Connection
      run: |
        echo "Testing SSH connection to GitHub..."
        ssh -vT git@github.com

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Changing directory to the project..."
          cd /var/www/lovebird4u.com/DatingAppFlutter-Backend
          echo "Pulling latest changes from GitHub..."
          git pull origin main
          echo "Installing npm dependencies..."
          npm install
          echo "Restarting the application..."
          pm2 restart lovebird-backend
          echo "Saving PM2 process list..."
          pm2 save
