name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "SSH directory created."

    - name: Add SSH Key
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "SSH key added successfully."

    - name: Set GitHub SSH Key for the server
      run: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo "GitHub SSH key scanned."

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Add this line to include the passphrase
        script: |
          cd /var/www/lovebird4u.com/DatingAppFlutter-Backend
          git pull origin main
          npm install
          pm2 restart lovebird-backend
          pm2 save
