name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        # Uncomment if your SSH key has a passphrase
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /var/www/lovebird4u.com/DatingAppFlutter-Backend
          git remote add origin git@github.com:malitha23/DatingAppFlutter-Backend.git
          git pull origin main
          npm install
          pm2 restart lovebird-backend # Restart your app using PM2 (or any other process manager)
          pm2 save
