name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Add SSH Key
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Set GitHub SSH Key for the server
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ~/.ssh/id_rsa
        passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Include this only if your SSH key has a passphrase
        script: |
          cd /var/www/lovebird4u.com/DatingAppFlutter-Backend
          git pull origin main
          npm install
          pm2 restart lovebird-backend # Restart your app using PM2 (or any other process manager)
          pm2 save
